# Python Basics Refresher

### Function Practice

### Write a function square(x) that returns the square of a number

In [1]:
def sqr (x):
    sqr = x*x
    return sqr 

In [2]:
sqr(4)

16

### List Manipulation

### Write a function double_list(lst) that returns a list with each element doubled

In [4]:
def double_list(lst):
    return [2 * x for x in lst]
print(double_list([1,2,3,4]))

[2, 4, 6, 8]


### Numpy Introduction

### Write a function `vector_norm(v)` that takes a NumPy array and returns its Euclidean norm.

In [12]:
import numpy as np
def vector_norm(v):
    return np.linalg.norm(v)

In [13]:
vec = np.array([3,4])

In [14]:
print(vector_norm(vec))

5.0


# Rotation Matrices 


### Rotation Matrix about X-axis

#### Implement a function `get_RX(theta)` to return a 3×3 rotation matrix for rotation by `theta` radians about the X-axis.

### Basic Trignometry in Python 

In [3]:
import numpy as np

def sin_cos (a_d):
    a_r = np.radians(a_d)
    return np.sin(a_r),np.cos(a_r)

In [3]:
x = 45 
sin, cos = sin_cos(x)
print(sin,cos)

0.7071067811865475 0.7071067811865476


### Convert Degrees to Radians

In [10]:
def deg_rad(deg):
    return deg * np.pi /180 

In [5]:
deg_rad(180)

3.141592653589793

### Create a 2D Rotation Matrix

In [9]:
def d_rot(theta):
    x = deg_rad(theta)
    return np.array([[np.cos(x), -np.sin(x)],
               [np.sin(x), np.cos(x)]])

In [7]:
print(d_rot(90))

[[ 6.123234e-17 -1.000000e+00]
 [ 1.000000e+00  6.123234e-17]]


### Implement a function that converts degrees to radians, as numpy functions work with radians.

In [8]:
def deg_rad (x):
    return np.radians(x)

In [9]:
x = 180
rad = deg_rad(x)
print(rad)

3.141592653589793


## Apply 2D Rotation to a Point

In [11]:
def rot_point(point, angle):
    R = d_rot(angle)
    return R @ point 


In [12]:
point = np.array([1,0])
rotated_point = rot_point(point,45)
print(rotated_point)

[0.70710678 0.70710678]


### Implement rotation matrices for X, Y, and Z axes separately.

In [36]:
def rot_matrix_x(theta):
    x = deg_rad(theta)
    print(x)
    return np.array([[1,0,0],
                    [0,np.cos(x),-np.sin(x)],
                    [0,np.sin(x),np.cos(x)]])


def rot_matrix_y(theta):
    x = deg_rad(theta)
    return np.array([[np.cos(x),0,np.sin(x)],
                     [0,1,0],
                     [-np.sin(x),0,np.cos(x)]])

def rot_matrix_z(theta):
    x = deg_rad(theta)
    return np.array([[np.cos(x),-np.sin(x),0],
                     [np.sin(x),np.cos(x),0],
                     [0,0,1]])

In [27]:
print(rot_matrix_x(90))

1.5707963267948966
[[ 1.000000e+00  0.000000e+00  0.000000e+00]
 [ 0.000000e+00  6.123234e-17 -1.000000e+00]
 [ 0.000000e+00  1.000000e+00  6.123234e-17]]


In [30]:
print(rot_matrix_y(90))

[[ 6.123234e-17  0.000000e+00  1.000000e+00]
 [ 0.000000e+00  1.000000e+00  0.000000e+00]
 [-1.000000e+00  0.000000e+00  6.123234e-17]]


In [31]:
print(rot_matrix_z(90))

[[ 6.123234e-17 -1.000000e+00  0.000000e+00]
 [ 1.000000e+00  6.123234e-17  0.000000e+00]
 [ 0.000000e+00  0.000000e+00  1.000000e+00]]


# Applying 3D Rotations 

### Rotate a 3D vector using a given rotation matrix.

In [37]:
vector = np.array([1,0,0])


In [44]:
r_v_y = rot_matrix_y(90) @ vector 
print(r_v_y)

[ 6.123234e-17  0.000000e+00 -1.000000e+00]


In [54]:
Rx_0 = rot_matrix_x(0)
Ry_0 = rot_matrix_y(0)
Rz_0 = rot_matrix_z(0)
print(Rx_0)

0.0
[[ 1.  0.  0.]
 [ 0.  1. -0.]
 [ 0.  0.  1.]]


In [55]:
print(Ry_0)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [-0.  0.  1.]]


In [56]:
print(Rz_0)

[[ 1. -0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [66]:
# Import required package
import numpy as np

# Taking a 3 * 3 matrix
A = np.array([[6, 1, 1],
			[4, -2, 5],
			[2, 8, 7]])

# Calculating the inverse of the matrix
A_Inv = np.linalg.inv(A)

# Calculate transpose 
A_ts = A.transpose()

print(A_Inv)
print(A_ts)

[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]
[[ 6  4  2]
 [ 1 -2  8]
 [ 1  5  7]]


# Homogenous Transformation Matrices

In [71]:
I = np.eye(4)

In [72]:
print(I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [73]:
def translation_matrix(x, y, z):
    T = np.eye(4)  # Start with identity
    T[:3, 3] = [x, y, z]  # Set translation part
    return T

# Example usage
T = translation_matrix(1, 2, 3)
print("Translation Matrix:\n", T)


Translation Matrix:
 [[1. 0. 0. 1.]
 [0. 1. 0. 2.]
 [0. 0. 1. 3.]
 [0. 0. 0. 1.]]


In [74]:
def homogeneous_from_rotation(R):
    T = np.eye(4)
    T[:3, :3] = R  # Insert rotation part
    return T

# Example with an identity rotation matrix
R = np.eye(3)
T = homogeneous_from_rotation(R)
print("Homogeneous Transformation Matrix:\n", T)


Homogeneous Transformation Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
