### Rotate a 3D vector using a given rotation matrix.

In [37]:
vector = np.array([1,0,0])


In [44]:
r_v_y = rot_matrix_y(90) @ vector 
print(r_v_y)

[ 6.123234e-17  0.000000e+00 -1.000000e+00]


In [54]:
Rx_0 = rot_matrix_x(0)
Ry_0 = rot_matrix_y(0)
Rz_0 = rot_matrix_z(0)
print(Rx_0)

0.0
[[ 1.  0.  0.]
 [ 0.  1. -0.]
 [ 0.  0.  1.]]


In [55]:
print(Ry_0)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [-0.  0.  1.]]


In [56]:
print(Rz_0)

[[ 1. -0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [66]:
# Import required package
import numpy as np

# Taking a 3 * 3 matrix
A = np.array([[6, 1, 1],
			[4, -2, 5],
			[2, 8, 7]])

# Calculating the inverse of the matrix
A_Inv = np.linalg.inv(A)

# Calculate transpose 
A_ts = A.transpose()

print(A_Inv)
print(A_ts)

[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]
[[ 6  4  2]
 [ 1 -2  8]
 [ 1  5  7]]


In [72]:
print(I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [73]:
def translation_matrix(x, y, z):
    T = np.eye(4)  # Start with identity
    T[:3, 3] = [x, y, z]  # Set translation part
    return T

# Example usage
T = translation_matrix(1, 2, 3)
print("Translation Matrix:\n", T)


Translation Matrix:
 [[1. 0. 0. 1.]
 [0. 1. 0. 2.]
 [0. 0. 1. 3.]
 [0. 0. 0. 1.]]


In [74]:
def homogeneous_from_rotation(R):
    T = np.eye(4)
    T[:3, :3] = R  # Insert rotation part
    return T

# Example with an identity rotation matrix
R = np.eye(3)
T = homogeneous_from_rotation(R)
print("Homogeneous Transformation Matrix:\n", T)


Homogeneous Transformation Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
